# Generated by Django 3.2.18 on 2023-03-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-09-01'),
            preserve_default=False,
        ),
    ]
